FROM node:22-alpine AS frontend-build

WORKDIR /workspace

COPY package.json package-lock.json ./
RUN npm ci

COPY index.html tsconfig.json tsconfig.node.json vite.config.ts ./
COPY src ./src
COPY public ./public
RUN npm run build

FROM caddy:2-alpine

COPY Caddyfile.local /etc/caddy/Caddyfile
COPY --from=frontend-build /workspace/dist /srv

EXPOSE 80
